# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57cfd0574d065e4be2c3bb37bd0d3dc9ab7a7b2e3b9a7e5e2511b11ef45caac8747e2ae903a5d480c0f5003839892aa830b0b0ae989267c69bc61ecfe0e711e9

test:
  secret_key_base: 19901665f64fd078637327c571874e30a3ae7b791fdbd126db82313cd33430027bb39d9a03e20168659c5f90b471ee0a324692df2d7b692b69354a06f6dfe770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
